import os 
from dotenv import load_dotenv
load_dotenv()
from fastapi import APIRouter, Header, HTTPException, BackgroundTasks, Request
from pydantic import BaseModel, ValidationError
from typing import List, Optional, Union # <--- ADD Union here

import httpx
import logging
import json 

from honeypot.AI import analyze_and_reply
from honeypot.utils import extract_intelligence
from honeypot.store import get_or_create_session, update_session

router = APIRouter()
logger = logging.getLogger("uvicorn")

# --- 1. Fix the Data Models ---

class MessageDetail(BaseModel):
    sender: str
    text: str
    timestamp: Union[str, int]  # <--- FIXED: Accepts both 1770... (int) and "2026..." (str)

class Metadata(BaseModel):
    channel: Optional[str] = None
    language: Optional[str] = None
    locale: Optional[str] = None

class ScamRequest(BaseModel):
    sessionId: str
    message: MessageDetail
    conversationHistory: Optional[List[MessageDetail]] = [] 
    metadata: Optional[Metadata] = None

# --- Callback Function ---
async def send_final_report(payload: dict):
    url = "https://hackathon.guvi.in/api/updateHoneyPotFinalResult"
    async with httpx.AsyncClient() as client:
        try:
            logger.info(f"🚀 Sending Final Report for Session: {payload['sessionId']}")
            response = await client.post(url, json=payload, timeout=10.0)
            logger.info(f"✅ Report Status: {response.status_code} | Body: {response.text}")
        except Exception as e:
            logger.error(f"❌ Failed to report: {e}")

# --- Main Endpoint ---
@router.post("/chat")
async def chat_handler(request: Request, background_tasks: BackgroundTasks, x_api_key: str = Header(None)):
    
    # 1. READ RAW BODY
    try:
        raw_body = await request.json()
        # print(json.dumps(raw_body, indent=2)) # Uncomment only if debugging
    except Exception as e:
        raise HTTPException(status_code=400, detail="Invalid JSON")

    # 2. Auth Check
    # Ensure you have API_KEY in your .env file
    valid_key = os.environ.get("API_KEY")
    if valid_key and x_api_key != valid_key:
        print(f"❌ Auth Failed. Expected: {valid_key}, Got: {x_api_key}")
        raise HTTPException(status_code=401, detail="Unauthorized")

    # 3. Validate with Fixed Model
    try:
        payload = ScamRequest(**raw_body)
    except ValidationError as e:
        print(f"❌ VALIDATION ERROR: {e}")
        # Return a safe fallback so the platform doesn't show 'Error'
        return {
            "status": "success",
            "reply": "System processing error. Please retry."
        }

    # --- LOGIC STARTS HERE ---
    
    user_msg = payload.message.text
    session_id = payload.sessionId
    
    # State & Intelligence
    get_or_create_session(session_id)
    new_intel = extract_intelligence(user_msg)
    current_state = update_session(session_id, new_intel)

    # AI Processing
    history = payload.conversationHistory if payload.conversationHistory else []
    ai_result = await analyze_and_reply(user_msg, history)
    
    current_state["totalMessagesExchanged"] += 1
    
    # Check Logic
    has_critical_info = (len(current_state["extractedIntelligence"]["upiIds"]) > 0 or 
                         len(current_state["extractedIntelligence"]["bankAccounts"]) > 0)
    is_long_conversation = current_state["totalMessagesExchanged"] >= 8
    
    if (has_critical_info or is_long_conversation) and not current_state["report_sent"]:
        final_payload = {
            "sessionId": session_id,
            "scamDetected": True,
            "totalMessagesExchanged": current_state["totalMessagesExchanged"],
            "extractedIntelligence": current_state["extractedIntelligence"],
            "agentNotes": "Auto-generated by HoneyPot AI"
        }
        background_tasks.add_task(send_final_report, final_payload)
        current_state["report_sent"] = True

    return {
        "status": "success",
        "reply": ai_result.get("reply", "...")
    }