import os 
from dotenv import load_dotenv
load_dotenv()
from fastapi import APIRouter, Header, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import List, Optional, Union # <--- Critical Import
import httpx
import logging

# Import your modules
from honeypot.AI import analyze_and_reply
from honeypot.utils import extract_intelligence
from honeypot.store import get_or_create_session, update_session

router = APIRouter()
logger = logging.getLogger("uvicorn")

# --- 1. FIXED DATA MODELS ---

class MessageDetail(BaseModel):
    sender: str
    text: str
    # ✅ FIX: Accepts 1770138904741 (int) AND "2026-02-03" (str)
    timestamp: Union[str, int]  

class Metadata(BaseModel):
    channel: Optional[str] = None
    language: Optional[str] = None
    locale: Optional[str] = None

class ScamRequest(BaseModel):
    sessionId: str
    message: MessageDetail
    # ✅ FIX: Default to empty list if None is sent
    conversationHistory: Optional[List[MessageDetail]] = [] 
    metadata: Optional[Metadata] = None

# --- Callback Function ---
async def send_final_report(payload: dict):
    url = "https://hackathon.guvi.in/api/updateHoneyPotFinalResult"
    async with httpx.AsyncClient() as client:
        try:
            logger.info(f"🚀 Sending Final Report for Session: {payload['sessionId']}")
            response = await client.post(url, json=payload, timeout=10.0)
            logger.info(f"✅ Report Status: {response.status_code} | Body: {response.text}")
        except Exception as e:
            logger.error(f"❌ Failed to report: {e}")

# --- 2. RESTORED ENDPOINT ---
# We switched 'request: Request' back to 'payload: ScamRequest'
# This brings back the input box in Swagger UI!
@router.post("/chat")
async def chat_handler(payload: ScamRequest, background_tasks: BackgroundTasks, x_api_key: str = Header(None)):
    
    # 1. Auth Check
    valid_key = os.environ.get("API_KEY") # Ensure this matches your .env
    # If using local testing without .env, you can comment the check out temporarily
    if valid_key and x_api_key != valid_key:
        raise HTTPException(status_code=401, detail="Unauthorized")

    # 2. Logic (Clean and Simple)
    user_msg = payload.message.text
    session_id = payload.sessionId
    
    print(f"✅ Received Message: {user_msg}") # Success Log

    # State & Intelligence
    get_or_create_session(session_id)
    new_intel = extract_intelligence(user_msg)
    current_state = update_session(session_id, new_intel)

    # AI Processing
    history = payload.conversationHistory if payload.conversationHistory else []
    ai_result = await analyze_and_reply(user_msg, history)
    
    current_state["totalMessagesExchanged"] += 1
    
    # 3. Check Logic for Reporting
    has_critical_info = (len(current_state["extractedIntelligence"]["upiIds"]) > 0 or 
                         len(current_state["extractedIntelligence"]["bankAccounts"]) > 0)
    is_long_conversation = current_state["totalMessagesExchanged"] >= 8
    
    if (has_critical_info or is_long_conversation) and not current_state["report_sent"]:
        final_payload = {
            "sessionId": session_id,
            "scamDetected": True,
            "totalMessagesExchanged": current_state["totalMessagesExchanged"],
            "extractedIntelligence": current_state["extractedIntelligence"],
            "agentNotes": "Auto-generated by HoneyPot AI"
        }
        background_tasks.add_task(send_final_report, final_payload)
        current_state["report_sent"] = True

    return {
        "status": "success",
        "reply": ai_result.get("reply", "...")
    }